/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#4d4870",
        "sale-red": "#E30613",
        "on-tertiary-fixed": "#302b51",
        "inverse-on-surface": "#9b9da1",
        error: "#a83836",
        "inverse-surface": "#0c0e11",
        "outline-variant": "#adb2ba",
        primary: "#3d6288",
        "on-secondary-container": "#465363",
        "on-primary-fixed-variant": "#254b71",
        "surface-bright": "#f8f9fe",
        "tertiary-fixed": "#cec6f6",
        "on-error-container": "#6e0a12",
        "trust-blue": "#0033A0",
        "surface-variant": "#dee3eb",
        "surface-dim": "#d5dae3",
        "primary-fixed": "#a5caf6",
        "surface-tint": "#3d6288",
        "primary-fixed-dim": "#98bce7",
        "on-tertiary-container": "#443f66",
        "surface-container-high": "#e5e8f0",
        "tertiary-fixed-dim": "#c0b9e8",
        "surface-container-low": "#f1f3f9",
        "on-secondary": "#f7f9ff",
        "on-error": "#fff7f6",
        "mass-yellow": "#FFD100",
        "surface-container-highest": "#dee3eb",
        "secondary-container": "#d6e4f7",
        "on-surface-variant": "#5a6067",
        "surface-container": "#ebeef5",
        "tertiary-container": "#cec6f6",
        "on-secondary-fixed": "#344050",
        secondary: "#536070",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#d6e4f7",
        "on-tertiary": "#fcf7ff",
        "primary-container": "#a5caf6",
        "on-primary-fixed": "#002e50",
        "secondary-fixed-dim": "#c8d5e9",
        "error-container": "#fa746f",
        "on-surface": "#2d333a",
        surface: "#f8f9fe",
        "surface-grey": "#F4F4F4",
        background: "#f8f9fe",
        outline: "#767b83",
        "on-primary-container": "#1a4267",
        "on-primary": "#ffffff",
        tertiary: "#605a83",
        "inverse-primary": "#a5caf6",
        "on-secondary-fixed-variant": "#505d6d",
        "on-background": "#2d333a",
        "trust-blue-dark": "#002266",
        "primary-dim": "#30557b",
        "error-dim": "#67040d",
        "secondary-dim": "#475464",
        "tertiary-dim": "#534e77"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px"
      },
      boxShadow: {
        // Design system "Barrio Moderno" — Level 1: ambient shadow tinted trust-blue
        "level-1": "0 4px 16px 0 rgba(0, 51, 160, 0.12)",
        "level-2": "0 8px 28px 0 rgba(0, 51, 160, 0.18)"
      },
      spacing: {
        gutter: "16px",
        base: "8px",
        "container-max": "1280px",
        "section-gap": "80px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        md: "16px",
        xs: "4px",
        sm: "8px",
        lg: "24px",
        xl: "32px",
        margin: "24px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "price-display": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["28px", {lineHeight: "36px", fontWeight: "700"}],
        "headline-lg": ["32px", {lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700"}],
        "headline-xl": ["48px", {lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800"}],
        "headline-md": ["24px", {lineHeight: "32px", fontWeight: "700"}],
        "headline-sm": ["20px", {lineHeight: "28px", fontWeight: "700"}],
        "label-bold": ["14px", {lineHeight: "20px", fontWeight: "600"}],
        "label-md": ["12px", {lineHeight: "16px", letterSpacing: "0.5px", fontWeight: "500"}],
        "body-md": ["16px", {lineHeight: "24px", fontWeight: "400"}],
        "body-lg": ["18px", {lineHeight: "28px", fontWeight: "400"}],
        "price-display": ["40px", {lineHeight: "40px", letterSpacing: "-0.04em", fontWeight: "800"}]
      }
    }
  },
  plugins: [],
}
